version: '3.8'

services:
  # MinIO 服务
  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: unless-stopped
    ports:
      - "9000:9000"      # MinIO API端口
      - "9001:9001"      # MinIO Console端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # RabbitMQ 服务 (已存在，这里重新定义)
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-server
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP端口
      - "15672:15672"    # 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  default:
    name: file-processing-network